In [79]:
### Author : Florian Guillot
### Project : Advent of Code 2021, Day 4
### https://adventofcode.com/2021/day/4
### 04/12/2021
### title : Giant Squid
### This code can be used as you want, enjoy it (if you enjoy code in general, and this one, you know what I mean) 

Classical imports

In [80]:
import pandas as pd
import numpy as np
dim = 5 #(dimension of the bingo grids)

## Read the file and arrange the data
---

In [81]:
# We read the file
#with open('input4b.txt') as f: # Choose this line for tests, using data given in the example
with open('input4.txt') as f: #Choose this line for the real exercise
    numbers = list(map(int,  f.readline().replace("\n","").split(","))) #the first line given, transformed in a list of the characters
    lines = f.read().splitlines() # For now the other lines will be put in a list of characters, one element per line
print("Numbers :", numbers)
print("First non-empty line", lines[1])

Numbers : [76, 69, 38, 62, 33, 48, 81, 2, 64, 21, 80, 90, 29, 99, 37, 15, 93, 46, 75, 0, 89, 56, 58, 40, 92, 47, 8, 6, 54, 96, 12, 66, 83, 4, 70, 19, 17, 5, 50, 52, 45, 51, 18, 27, 49, 71, 28, 86, 74, 77, 11, 20, 84, 72, 23, 31, 16, 78, 91, 65, 87, 79, 73, 94, 24, 68, 63, 9, 88, 82, 30, 42, 60, 13, 67, 85, 44, 59, 7, 53, 22, 1, 26, 41, 61, 55, 43, 39, 3, 35, 25, 34, 57, 10, 14, 32, 97, 95, 36, 98]
First non-empty line 17 45 62 28 73


In [82]:
# We clean the input from char to integers and create a list of np.array, each array is a bingo grid
grids=[]
for index,line in enumerate(lines):
    if line =="": # For each empty line, we know the 5 next will be a new grid 5x5
        grids.append(np.array(pd.DataFrame([lines[index+i].split() for i in range(1,6)]).astype((int))))
print("The first grid:\n", grids[0])


The first grid:
 [[17 45 62 28 73]
 [39 12  0 52  5]
 [87 48 50 85 44]
 [66 57 78 94  3]
 [91 37 69 16  1]]


In [83]:
# We add a 3rd dimension to the grids, filled with only 0 for now, for each grid ( to check if the number has been out. If the number in the grid is checked, then 1 will replace 0)
ngrids=[] #The new 3 dimension grids
for grid in grids:
    ngrids.append(np.dstack((grid.reshape(5,5,1), np.zeros((5,5)))))
print('The first grid:\n', ngrids[0])

The first grid:
 [[[17.  0.]
  [45.  0.]
  [62.  0.]
  [28.  0.]
  [73.  0.]]

 [[39.  0.]
  [12.  0.]
  [ 0.  0.]
  [52.  0.]
  [ 5.  0.]]

 [[87.  0.]
  [48.  0.]
  [50.  0.]
  [85.  0.]
  [44.  0.]]

 [[66.  0.]
  [57.  0.]
  [78.  0.]
  [94.  0.]
  [ 3.  0.]]

 [[91.  0.]
  [37.  0.]
  [69.  0.]
  [16.  0.]
  [ 1.  0.]]]


## PART 1
---

### Function to verifie if a grid (array (5,5,2)) verifies the winning condition 
--

Winning condition : A column or line with all the numbers checked. In our code it means that in the third dimension, we will have only "1"

In [84]:
# We create a function that verifies if the grid meets the win condition
def win(grid): # Grid is a (5,5,2) numpy array
    for i in range(5): # Verification for all the lines and columns, 5 of each
        if np.sum(grid[:,:,1], axis=1)[i]==dim or np.sum(grid[:,:,1], axis=0)[i]==dim: # If in a line or column of a grid, addition of the third dimension is 5, it means we will have only 1, it means all the numbers are checked : winning condition ! 
            res = np.sum(np.multiply((grid[:,:,1]-1)*(-1), grid[:,:,0])) # We use that for binary condition (0 or 1) not x = (x-1)*(-1). Res is the addition of all the unchecked numbers, so checked number mutiplied by zero wii be zero
            return (True,res,grid)
    return (False,"no result")

### Loop over the data and play the bingo game ! 

In [85]:
test_continue =True # boolean condition, will be True when a winning condition appears
for number in numbers: # Loop over the random numbers given through the game
    if not test_continue: break
    print("test for number", number) 
    for grid_number,grid in enumerate(ngrids): # Then we loop over the grids
        if not test_continue: break
        print("test for grid", grid_number)
        for (x,y) ,value in np.ndenumerate(grid[:,:,0]): # For each grid we loop over the numbers
            if not test_continue: break
            if value==number: # If the number in the grid is the same than the number announced:
                ngrids[grid_number][x,y,1]=1 # We check it in the third dimension
                if win(grid)[0]: # We verify immediately the winning conditions
                    print("the result is", win(grid)[1]*number, "with the grid",grid) #If winning condition, bingo! we show the result
                    test_continue = False
                    break 

test for number 76
test for grid 0
test for grid 1
test for grid 2
test for grid 3
test for grid 4
test for grid 5
test for grid 6
test for grid 7
test for grid 8
test for grid 9
test for grid 10
test for grid 11
test for grid 12
test for grid 13
test for grid 14
test for grid 15
test for grid 16
test for grid 17
test for grid 18
test for grid 19
test for grid 20
test for grid 21
test for grid 22
test for grid 23
test for grid 24
test for grid 25
test for grid 26
test for grid 27
test for grid 28
test for grid 29
test for grid 30
test for grid 31
test for grid 32
test for grid 33
test for grid 34
test for grid 35
test for grid 36
test for grid 37
test for grid 38
test for grid 39
test for grid 40
test for grid 41
test for grid 42
test for grid 43
test for grid 44
test for grid 45
test for grid 46
test for grid 47
test for grid 48
test for grid 49
test for grid 50
test for grid 51
test for grid 52
test for grid 53
test for grid 54
test for grid 55
test for grid 56
test for grid 57
test 

## PART 2
---

In [86]:
ngrids2=[] #The new 3 dimension grids
for grid in grids:
    ngrids2.append(np.dstack((grid.reshape(5,5,1), np.zeros((5,5)))))
print('The first grid:\n', ngrids2[0])

The first grid:
 [[[17.  0.]
  [45.  0.]
  [62.  0.]
  [28.  0.]
  [73.  0.]]

 [[39.  0.]
  [12.  0.]
  [ 0.  0.]
  [52.  0.]
  [ 5.  0.]]

 [[87.  0.]
  [48.  0.]
  [50.  0.]
  [85.  0.]
  [44.  0.]]

 [[66.  0.]
  [57.  0.]
  [78.  0.]
  [94.  0.]
  [ 3.  0.]]

 [[91.  0.]
  [37.  0.]
  [69.  0.]
  [16.  0.]
  [ 1.  0.]]]


In [87]:
# We apply the game and calculate the search of each grid when it wins
fres = []
end_it = False
for number in numbers: # Loop over the random numbers given through the game
    if end_it: break
    print("test for number", number) 
    for grid_number,grid in enumerate(ngrids2): # Then we loop over the grids
        print("test for grid", grid_number)
        if len(ngrids2) == 1 and win(ngrids2[0])[0]:
            print ("there is only one grid left, it's just completed" )
            end_it = True
            break
        for (x,y) ,value in np.ndenumerate(grid[:,:,0]): # For each grid we loop over the numbers
            if value==number: # If the number in the grid is the same than the number announced:
                ngrids2[grid_number][x,y,1]=1 # We check it in the third dimension
                if win(grid)[0]: # We verify immediately the winning conditions
                    print("the grid", grid_number, "is completed with a result", win(grid)[1]*number) #If winning condition, bingo! we show the result
                    fres.append((grid_number,win(grid)[1]*number))
                    break

test for number 76
test for grid 0
test for grid 1
test for grid 2
test for grid 3
test for grid 4
test for grid 5
test for grid 6
test for grid 7
test for grid 8
test for grid 9
test for grid 10
test for grid 11
test for grid 12
test for grid 13
test for grid 14
test for grid 15
test for grid 16
test for grid 17
test for grid 18
test for grid 19
test for grid 20
test for grid 21
test for grid 22
test for grid 23
test for grid 24
test for grid 25
test for grid 26
test for grid 27
test for grid 28
test for grid 29
test for grid 30
test for grid 31
test for grid 32
test for grid 33
test for grid 34
test for grid 35
test for grid 36
test for grid 37
test for grid 38
test for grid 39
test for grid 40
test for grid 41
test for grid 42
test for grid 43
test for grid 44
test for grid 45
test for grid 46
test for grid 47
test for grid 48
test for grid 49
test for grid 50
test for grid 51
test for grid 52
test for grid 53
test for grid 54
test for grid 55
test for grid 56
test for grid 57
test 

In [93]:
# We print the result, the last gridf is the one we search
for idx,elem in enumerate(fres):
    num_grid = elem[0]
    first_one=True
    for elem2 in fres[:idx]:
        if elem2[0]==num_grid: first_one=False
    if first_one:
        print(elem)
        
    

(69, 2496.0)
(45, 60060.0)
(83, 47950.0)
(47, 3875.0)
(64, 38000.0)
(29, 27872.0)
(36, 35505.0)
(13, 26775.0)
(89, 26520.0)
(27, 15102.0)
(40, 9666.0)
(41, 6084.0)
(76, 14526.0)
(18, 9828.0)
(21, 13743.0)
(86, 16686.0)
(87, 29057.0)
(5, 15148.0)
(14, 57362.0)
(2, 43216.0)
(16, 28194.0)
(62, 37962.0)
(7, 51898.0)
(90, 26411.0)
(8, 9581.0)
(95, 4763.0)
(15, 12840.0)
(82, 14100.0)
(63, 51492.0)
(72, 50736.0)
(74, 44604.0)
(93, 39984.0)
(94, 44772.0)
(6, 13869.0)
(22, 13915.0)
(25, 14329.0)
(56, 12696.0)
(17, 11501.0)
(59, 15655.0)
(31, 7584.0)
(32, 6336.0)
(65, 9344.0)
(0, 44772.0)
(57, 37037.0)
(50, 31200.0)
(55, 31005.0)
(35, 37758.0)
(39, 41238.0)
(70, 36714.0)
(91, 49677.0)
(9, 36340.0)
(24, 26465.0)
(42, 31995.0)
(44, 44161.0)
(96, 27650.0)
(99, 27594.0)
(73, 43240.0)
(49, 6408.0)
(68, 15744.0)
(78, 9144.0)
(79, 8736.0)
(85, 10656.0)
(30, 25976.0)
(81, 26452.0)
(88, 23800.0)
(84, 24192.0)
(33, 4833.0)
(43, 3555.0)
(52, 3240.0)
(67, 2529.0)
(92, 37400.0)
(3, 33210.0)
(61, 28864.0)
(71