In [184]:
### Author : Florian Guillot
### Project : Advent of Code 2021, Day 4
### https://adventofcode.com/2021/day/4
### 04/12/2021
### title : Giant Squid
### This code can be used as you want, enjoy it (if you enjoy code in general, and this one, you know what I mean) 

## Classical imports
---

In [185]:
import pandas as pd
import numpy as np
dim = 5 #(dimension of the bingo grids)

## Read the file and arrange the data
---

In [199]:
# We read the file
with open('input4b.txt') as f: # Choose this line for tests, using data given in the example
#with open('input4b.txt') as f: #Choose this line for the real exercise
    numbers = list(map(int,  f.readline().replace("\n","").split(","))) #the first line given, transformed in a list of the characters
    lines = f.read().splitlines() # For now the other lines will be put in a list of characters, one element per line
print("Numbers :", numbers)
print("First non-empty line", lines[1])

Numbers : [7, 4, 9, 5, 11, 17, 23, 2, 0, 14, 21, 24, 10, 16, 13, 6, 15, 25, 12, 22, 18, 20, 8, 19, 3, 26, 1]
First non-empty line 22 13 17 11  0


In [203]:
# We clean the input from char to integers and create a list of np.array, each array is a bingo grid
grids=[]
for index,line in enumerate(lines):
    if line =="": # For each empty line, we know the 5 next will be a new grid 5x5
        grids.append(np.array(pd.DataFrame([lines[index+i].split() for i in range(1,6)]).astype((int))))
print("The first grid:\n", grids[0])


The first grid:
 [[22 13 17 11  0]
 [ 8  2 23  4 24]
 [21  9 14 16  7]
 [ 6 10  3 18  5]
 [ 1 12 20 15 19]]


In [204]:
# We add a 3rd dimension to the grids, filled with only 0 for now, for each grid ( to check if the number has been out. If the number in the grid is checked, then 1 will replace 0)
ngrids=[] #The new 3 dimension grids
for grid in grids:
    ngrids.append(np.dstack((grid.reshape(5,5,1), np.zeros((5,5)))))
print('The first grid:\n', ngrids[0])

The first grid:
 [[[22.  0.]
  [13.  0.]
  [17.  0.]
  [11.  0.]
  [ 0.  0.]]

 [[ 8.  0.]
  [ 2.  0.]
  [23.  0.]
  [ 4.  0.]
  [24.  0.]]

 [[21.  0.]
  [ 9.  0.]
  [14.  0.]
  [16.  0.]
  [ 7.  0.]]

 [[ 6.  0.]
  [10.  0.]
  [ 3.  0.]
  [18.  0.]
  [ 5.  0.]]

 [[ 1.  0.]
  [12.  0.]
  [20.  0.]
  [15.  0.]
  [19.  0.]]]


## Function to verifie if a grid (array (5,5,2)) verifies the winning condition 
---
Winning condition : A column or line with all the numbers checked. In our code it means that in the third dimension, we will have only "1"

In [205]:
# We create a function that verifies if the grid meets the win condition
def win(grid): #grid is a (5,5,2) numpy array
    for i in range(5): # Verification for all the lines and columns, 5 of each
        if np.sum(grid[:,:,1], axis=1)[i]==dim or np.sum(grid[:,:,1], axis=0)[i]==dim: # If in a line or column of a grid, addition of the third dimension is 5, it means we will have only 1, it means all the numbers are checked : winning condition ! 
            res = np.sum(np.multiply((grid[:,:,1]-1)*(-1), grid[:,:,0])) #We use that for binary condition (0 or 1) not x = (x-1)*(-1). Res is the addition of all the unchecked numbers, so checked number mutiplied by zero wii be zero
            return (True,res,grid)
        else:
            return (False,"no result")

## Loop over the data and play the bingo game ! 
---

In [190]:
test_continue =True # boolean condition, will be True when a winning condition appears
for number in numbers: # Loop over the random numbers given through the game
    if not test_continue: break
    print("test for number", number) 
    for grid_number,grid in enumerate(ngrids): # Then we loop over the grids
        if not test_continue: break
        print("test for grid", grid_number)
        for (x,y) ,value in np.ndenumerate(grid[:,:,0]): # For each grid we loop over the numbers
            if not test_continue: break
            if value==number: # If the number in the grid is the same than the number announced:
                ngrids[grid_number][x,y,1]=1 # We check it in the third dimension
                if win(grid)[0]: # We verify immediately the winning conditions
                    print("the result is", win(grid)[1]*number, "with the grid",grid) #If winning condition, bingo! we show the result
                    test_continue = False
                    break 

test for number 7
test for grid 0
test for grid 1
test for grid 2
test for number 4
test for grid 0
test for grid 1
test for grid 2
test for number 9
test for grid 0
test for grid 1
test for grid 2
test for number 5
test for grid 0
test for grid 1
test for grid 2
test for number 11
test for grid 0
test for grid 1
test for grid 2
test for number 17
test for grid 0
test for grid 1
test for grid 2
test for number 23
test for grid 0
test for grid 1
test for grid 2
test for number 2
test for grid 0
test for grid 1
test for grid 2
test for number 0
test for grid 0
test for grid 1
test for grid 2
test for number 14
test for grid 0
test for grid 1
test for grid 2
test for number 21
test for grid 0
test for grid 1
test for grid 2
test for number 24
test for grid 0
test for grid 1
test for grid 2
the result is 4512.0 with the grid [[[14.  1.]
  [21.  1.]
  [17.  1.]
  [24.  1.]
  [ 4.  1.]]

 [[10.  0.]
  [16.  0.]
  [15.  0.]
  [ 9.  1.]
  [19.  0.]]

 [[18.  0.]
  [ 8.  0.]
  [23.  1.]
  [26. 